image: docker:17.05.0
stages:
  - build
before_script:
  - apk update
  - apk add bash tar rsync git curl make file
  - sed -i -e '/ linux\/arm/ s/^/#/' hack/lib/golang.sh 
  - sed -i -e '/ linux\/s390/ s/^/#/' hack/lib/golang.sh 
  - sed -i -e '/ linux\/386/ s/^/#/' hack/lib/golang.sh 
  - sed -i -e '/ linux\/ppc64le/ s/^/#/' hack/lib/golang.sh 
  - sed -i -e '/ darwin\/amd64/ s/^/#/' hack/lib/golang.sh 
  - sed -i -e '/ darwin\/386/ s/^/#/' hack/lib/golang.sh 
  - sed -i -e '/ windows\/386/ s/^/#/' hack/lib/golang.sh 
  - sed -i -e '/ windows\/amd64/ s/^/#/' hack/lib/golang.sh 
  - sed -i -e 's/kube::release::package_tarballs//g' ./build/release.sh
build:
  stage: build
  variables:
    KUBE_DOCKER_REGISTRY: "${CI_REGISTRY_IMAGE}"
    KUBE_DOCKER_IMAGE_TAG: "1.6.3+${CI_COMMIT_REF}-${CI_JOB_ID}"
    KUBE_FASTBUILD: "false"
    KUBE_RELEASE_RUN_TESTS: "n"
    KUBE_FASTBUILD: "n"
    KUBE_VERBOSE: "0"
    FEDERATION: "false"
  script:
    - ./build/release.sh || sleep 99999
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker push "$CI_REGISTRY_IMAGE/hyperkube-amd64:$KUBE_DOCKER_IMAGE_TAG"
    - cat > ci.vars <<EOF
        export TF_VAR_kubelet_image_url="$CI_REGISTRY_IMAGE/hyperkube-amd64"
        export TF_VAR_kubelet_image_tag="$KUBE_DOCKER_IMAGE_TAG"
        EOF
  artifacts:
    name: "${CI_JOB_NAME}.${CI_PIPELINE_ID}.${CI_JOB_ID}"
    expire_in: 1 weeks
    paths:
      - _output/ci.vars
      - _output/dockerized
      - _output/images
